steps:
  - name: "Run tests"
    image: rust:1.42
    commands: 
      - sh
      - -c
      - cargo test

  - name: "Run linting"
    image: rust:1.42
    commands: 
      - sh 
      - -c 
      - rustup component add clippy --toolchain 1.42.0-x86_64-unknown-linux-gnu && cargo clippy -- -D warnings

  - name: "Release"
    image: gcr.io/kaniko-project/executor:latest
    branch: master
    args:
      - "--dockerfile=/app/Dockerfile"
      - "--context=dir:///app"
      - "--destination=jordanph/kubes-cd:latest"
    mountSecret:
      - name: docker-config
        mountPath: /kaniko/.docker
