steps:
  - name: "Run tests"
    image: rust:1.42
    commands: 
      - sh
      - -c
      - cargo test

  - name: "Run linting"
    image: busybox
    commands: 
      - sh 
      - -c 
      - echo "hello world!" && sleep 5