steps:
  - block: ":rocket: Continue steps?"
    branches: "!master"

  - name: "Run tests"
    branch: "!master"
    image: jordanph/kubes-cd-dependencies-image:latest
    commands:
      - cargo test

  - name: "Run linting"
    branch: "!master"
    image: jordanph/kubes-cd-dependencies-image:latest
    commands:
      - cargo clippy -- -D warnings

  - name: "Run formatting"
    branch: "!master"
    image: jordanph/kubes-cd-dependencies-image:latest
    commands:
      - cargo fmt -- --check

  - name: "Release"
    image: gcr.io/kaniko-project/executor:latest
    branch: master
    args:
      - "--dockerfile=/app/Dockerfile"
      - "--context=dir:///app"
      - "--cache=true"
      - "--cache-repo=jordanph/kubes-cd-cache"
      - "--destination=jordanph/kubes-cd:latest"
    mountSecret:
      - name: docker-config
        mountPath: /kaniko/.docker

  - name: "Publish test dependencies image"
    image: gcr.io/kaniko-project/executor:latest
    branch: master
    args:
      - "--dockerfile=/app/dependencies.dockerfile"
      - "--context=dir:///app"
      - "--cache=true"
      - "--cache-repo=jordanph/kubes-cd-dependencies-image-cache"
      - "--destination=jordanph/kubes-cd-dependencies-image:latest"
    mountSecret:
      - name: docker-config
        mountPath: /kaniko/.docker
