steps:
  - name: "Run tests"
    branch: "!master"
    image: rust:1.42
    commands: 
      - cargo test

  - name: "Run linting"
    branch: "!master"
    image: rust:1.42
    commands: 
      - rustup component add clippy --toolchain 1.42.0-x86_64-unknown-linux-gnu
      - cargo clippy -- -D warnings

  - name: "Run formatting"
    branch: "!master"
    image: rust:1.42
    commands:
      - rustup component add rustfmt --toolchain 1.42.0-x86_64-unknown-linux-gnu
      - cargo fmt -- --check

  - name: "Release"
    image: gcr.io/kaniko-project/executor:latest
    branch: master
    args:
      - "--dockerfile=/app/Dockerfile"
      - "--context=dir:///app"
      - "--destination=jordanph/kubes-cd:latest"
    mountSecret:
      - name: docker-config
        mountPath: /kaniko/.docker
