---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubesci
automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubesci
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "pods/log"]
  verbs: ["get", "watch", "list", "create", "delete"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubesci
roleRef:
  kind: Role
  name: kubesci
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: kubesci

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubesci-deployment
  labels:
    app: kubesci-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubesci-controller
  template:
    metadata:
      labels:
        app: kubesci-controller
    spec:
      serviceAccount: kubesci
      serviceAccountName: kubesci
      containers:
      - name: kubesci-controller
        image: jordanph/kubesci:0.1
        ports:
        - containerPort: 3030
        env:
          - name: GITHUB_APPLICATION_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: github-ssh-key
                key: secret
          - name: APPLICATION_ID
            value: "43174"
          - name: NAMESPACE
            value: "kubesci"
          - name: RUST_LOG
            value: "debug"

---
apiVersion: v1
kind: Service
metadata:
  name: kubesci-controller
spec:
  selector:
    app: kubesci-controller
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3030
