steps:
  - name: "Run tests"
    image: jordanph/kubesci-dependencies-image:latest
    commands:
      - cargo test

  - name: "Run linting"
    image: jordanph/kubesci-dependencies-image:latest
    commands:
      - cargo clippy -- -D warnings

  - name: "Run formatting"
    image: jordanph/kubesci-dependencies-image:latest
    commands:
      - cargo fmt -- --check

  - wait

  - name: "Release"
    image: gcr.io/kaniko-project/executor:latest
    branch: master
    args:
      - "--dockerfile=/app/Dockerfile"
      - "--context=dir:///app"
      - "--cache=true"
      - "--cache-repo=jordanph/kubesci-cache"
      - "--destination=jordanph/kubesci:0.1.$(CHECK_RUN_ID)"
      - "--destination=jordanph/kubesci:0.1"
    mountSecret:
      - name: docker-config
        mountPath: /kaniko/.docker

  - name: "Publish test dependencies image"
    image: gcr.io/kaniko-project/executor:latest
    branch: master
    args:
      - "--dockerfile=/app/dependencies.dockerfile"
      - "--context=dir:///app"
      - "--cache=true"
      - "--cache-repo=jordanph/kubesci-dependencies-image-cache"
      - "--destination=jordanph/kubesci-dependencies-image:latest"
    mountSecret:
      - name: docker-config
        mountPath: /kaniko/.docker

  - block: "Publish image as latest"
    branch: master

  - name: "Release image as latest"
    image: gcr.io/kaniko-project/executor:latest
    branch: master
    args:
      - "--dockerfile=/app/Dockerfile"
      - "--context=dir:///app"
      - "--cache=true"
      - "--cache-repo=jordanph/kubesci-cache"
      - "--destination=jordanph/kubesci:latest"
    mountSecret:
      - name: docker-config
        mountPath: /kaniko/.docker
